### ISSUE TITLE
Converting Data into text format

### ISSUE THREAD

**Issue by IvanNextToJunior** [calebrwells/A-Swiftly-Tilting-Planet#6]
How can I make textual representation of Data and assign it to my properties in MVP pattern? I have an attachment array, which consists of two dictionary objects, each of them contains String properties in turn. Here's my model code:

class NetManager {

    private func makeRequest(urlString: String) -> URLRequest {
        let url = URL(string: urlString.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)!
        
        let urlRequest = URLRequest(url: url)
       
 return urlRequest
    }
    
 
    private func completionHandler(success: @escaping([Post]) -> Void, failure: (Int) -> Void, data: Data?, response: URLResponse?, error: Error?) {
        if error != nil {

        failure((error! as NSError).code)
       
        }
        
        else if data != nil {
        
            let jsonResponse = JSON(data!)
  
            DispatchQueue.main.async {

                let posts = self.makeNewPosts(json: jsonResponse)
                    success(posts)
                
            }
   
        
        }
        else {
            
            failure(666)
        }
    
    }
    
 
    func getMusic(success: @escaping([Post]) -> Void, failure: @escaping (Int) -> Void) {
       //delete the URL
        let urlString = "https://api.vk.com/method/wall.get.json?owner_id=-1212665&count&access_token=56dd06caf249416d3da146aae389e2d225ec807e69ba91170143fd43b747ed2bfe6702b568f711670eef8&v=5.71"
        
        let request = makeRequest(urlString: urlString)

        let task = URLSession.shared.dataTask(with: request) {[weak self] data, response, error
            in
         
            self?.completionHandler(success: success, failure: failure, data: data, response: response, error: error)
          
        }
        
        task.resume()
 
    }
    
}

extension NetManager {
 
    private func makeNewPosts(json: JSON) -> [Post] {
        var posts: [Post] = []
 
       var attachments: [Attachment] = []

        let itemsArray = json["response"]["items"].arrayValue

        for item in itemsArray {

     let text = item["text"].stringValue
 
let intValueOfDate = item["date"].int64Value
            let date = MyDateFormatter.getDateByStringFormatter(intValueOfDate)
 

             
            
            do {
                let jsonData = try json.rawData()
print(jsonData)
                
let jsonStr = String(data: jsonData, encoding: .utf8)!
let decoder = JSONDecoder()
              
 decoder.keyDecodingStrategy = .convertFromSnakeCase
               
 let result = try  decoder.decode([Attachment].self, from: jsonData)
                
print("Result is: \(result)")
                
           attachments = result
                
for attachment in attachments{
                  
  if let song = attachment.audio, let postPhoto = attachment.photo
                    {
                        let picture = postPhoto.photo75
                         
                        print("Song is: \(song.title), it's author is: \(song.artist), it lasts for: \(song.duration) minutes && seconds. You could download it on \(song.url). Image is: \(picture)")
                    }
                
                }

            }
           
                catch{
                print(error.localizedDescription)
                }

            
            
            let post = Post(text: text, date: date, attachments: attachments)
   
            posts.append(post)
        
            }
        return posts
    }

}

ViewController's code:
  func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        let cell = tableView.dequeueReusableCell(withIdentifier: kTableViewCellReusableIdentifier, for: indexPath) as! MusicTableViewCell
        let button = cell.playButton!
   
        button.actions(forTarget: button, forControlEvent: .touchUpInside)
        
        let post = store!.getPost(for: indexPath.row)
        
        if cell.dateLabel.text! == "" {
            
            cell.dateLabel.text = post.date
            
        }
            
        else {
            cell.dateLabel.text! = ""
            
let newText = post.date
           
 cell.dateLabel.text! = newText
        }
        
        cell.postTextLabel.text! = post.text
        
        if let postAttachments = post.attachments{
        
            for postAttachment in postAttachments{
           
            if let audio = postAttachment.audio{
               
              
                    
                    cell.singerLabel.text! = audio.artist
            
cell.titleLabel.text! = audio.title
            
cell.durationLabel.text! = audio.duration

                let imageString = imageOptionalString.photo75
                    
                if let imageURL = URL(string: imageString) {
                
                print(imageURL)
                   
 DispatchQueue.main.async {
  cell.groupView.sd_setImage(with: imageURL, completed: nil)
                    
}
                    }
                
            }
            
            
        
                
                
                
        
        
        
        }
        
        }
        }
        
        
        
        
        
        
        
        
        
        
        
        
        return cell
        
}
Presenter's function:

    func getPost(for index: Int) -> Post {
        
        return posts[index]
    }

I got error "The data couldn't be read because it isn't in the correct format

**Comment by mvlaursen** [comment]
Testing if I can reply to this email without going through Meetup.com <http://meetup.com/>...

**Comment by IvanNextToJunior** [comment]
Remove JSONDecoder and all other stuff. Just implement Codable in two(Audio and Photo) or four(Attachment, Audio, Photo, Post) classes. And put .array when retrieving attachments from JSON. And use standard swiftyJSON types
